### ISSUE TITLE
UnicodeEncodeError when running on Windows

### ISSUE THREAD

**Issue by leblancfg** [CamDavidsonPilon/python_packages_survey#4]
Running the script on Windows, I get the following error:

~~~python
Traceback (most recent call last):
  File "pip.py", line 111, in <module>
    post_to_api(data, ENDPOINT)
  File "pip.py", line 70, in post_to_api
    print("\u2728 Note: All private libraries are filtered out before hitting the database \u2728", end='\n\n')
  File "C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2728' in position 0: character maps to <undefined>
~~~

I believe Windows `print`s in its OS' local encoding, and forcing `print(EMOJI, encoding='utf-8')` still crashes ipython in my console.

### Possible courses of action
1. Remove emojis
2. Check what OS first, and strip string if needed. See e.g. how [pipenv does it](https://github.com/pypa/pipenv/blob/master/pipenv/environments.py#L78)

**Comment by CamDavidsonPilon** [comment]
ooo nice, obviously I'm on a non-windows so I would have missed this! Thanks @leblancfg :)
